language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PLUGIN_NAME=CakeNotify
    - REQUIRE="anklimsk/cakephp-console-installer"
    - DB=mysql
    - CAKE_REF=2.x
    - PHPUNIT=5.7.19

services:
  - mysql

matrix:
  include:
    - php: 7.3
      env:
        - CODECOVERAGE=1
    - php: 7.3
      env:
        - PHPCS=1
        - PHPCS_IGNORE=CakeInstaller,CakeBasicFunctions,CakeExtendTest,CakeConfigPlugin,CakeTheme,AssetCompress,Bs3Helpers,Queue,Shim,Tools
    - php: 7.3
      env:
        - FOC_VALIDATE=1

before_script:
  - git clone -b master https://github.com/anklimsk/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh
  - if [ -f "../cakephp/app/Console/cake" ]; then ../cakephp/app/Console/cake CakeInstaller setsecurkey --yes --app $(cd ../cakephp/app; pwd); fi
  - if [ -f "../cakephp/app/Plugin/CakeTheme/Config/asset_compress.local.ini" ]; then cp "../cakephp/app/Plugin/CakeTheme/Config/asset_compress.local.ini" "../cakephp/app/Config/asset_compress.ini"; fi
  - if [ -f "../cakephp/app/Config/email.php.default" ]; then cp ../cakephp/app/Config/email.php.default ../cakephp/app/Config/email.php; fi
  - if [ -f "../cakephp/app/Config/email.php" ]; then sed -i -r "s/('transport' => ')[a-z]+(')/\1Debug\2/i" ../cakephp/app/Config/email.php; fi

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
